# Generated by Django 5.2.7 on 2025-10-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nombre_cliente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='costo_ticket',
            new_name='ticket',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='RespuestaEncuesta',
        ),
    ]
