# Generated by Django 5.2.7 on 2025-10-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='num_eventos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
