# Generated by Django 5.2.7 on 2025-10-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_num_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='cliente',
        ),
    ]
