# Generated by Django 5.2.7 on 2025-10-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_nombre_cliente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_contacto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
