# Generated by Django 5.2.7 on 2025-10-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_contacto_cliente_num_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
