# Generated by Django 5.2.7 on 2025-11-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_encuestaevento_preguntacliente_respuestaencuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaencuesta',
            name='pregunta_texto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
