# Generated by Django 5.2.7 on 2025-11-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_respuestaencuesta_pregunta_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntacliente',
            name='opciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preguntacliente',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto libre'), ('opciones', 'Opciones (desplegable)')], default='texto', max_length=20),
        ),
    ]
